import { useState } from "react";
import { Card, Select, Button, Space, Grid } from "antd";
import { LeftOutlined, RightOutlined } from "@ant-design/icons";
import { useStore } from "../store";
const WEEKDAYS=["一","二","三","四","五","六","日"];
const dateStr=(y:number,m:number,d:number)=>`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
function addMonths(y:number,m:number,n:number){const total=y*12+m-1+n;return{y:Math.floor(total/12),m:total%12+1}}
function Month({year,month,days}:{year:number;month:number;days:string[]}){const count=new Date(year,month,0).getDate();const offset=(new Date(year,month-1,1).getDay()+6)%7;const cells=[...Array(offset).fill(null),...Array.from({length:count},(_,i)=>i+1)];return <div><div style={{textAlign:"center",marginBottom:6,color:"var(--text-secondary)"}}>{year} 年 {month} 月</div><div style={{display:"grid",gridTemplateColumns:"repeat(7, 28px)",gap:5}}>{WEEKDAYS.map(w=><small key={w} style={{textAlign:"center"}}>{w}</small>)}{cells.map((d,i)=>d===null?<span key={i}/>:<span key={i} title={dateStr(year,month,d)} style={{height:28,display:"grid",placeItems:"center",borderRadius:5,fontSize:11,background:days.includes(dateStr(year,month,d))?"var(--accent)":"var(--empty-day)",color:days.includes(dateStr(year,month,d))?"#fff":"var(--text-secondary)"}}>{d}</span>)}</div></div>}
export default function ContributionsPage(){const{studyDays}=useStore();const mobile=!Grid.useBreakpoint().md;const now=new Date();const cy=now.getFullYear(),cm=now.getMonth()+1;const initial=addMonths(cy,cm,-2);const[start,setStart]=useState(initial);const months=[0,1,2].map(n=>addMonths(start.y,start.m,n));const shift=(n:number)=>setStart(addMonths(start.y,start.m,n));return <main className="page-shell"><Card title="肝帝日历"><p style={{color:"var(--text-secondary)"}}>每一次完成都会点亮当天。稳定前进，比偶尔冲刺更重要。</p><Space wrap style={{marginBottom:20}}><Button aria-label="上一个月" icon={<LeftOutlined/>} onClick={()=>shift(-1)}/><Select value={start.y} onChange={y=>setStart({...start,y})} options={Array.from({length:11},(_,i)=>({value:cy-5+i,label:`${cy-5+i} 年`}))}/><Select value={start.m} onChange={m=>setStart({...start,m})} options={Array.from({length:12},(_,i)=>({value:i+1,label:`${i+1} 月`}))}/><Button aria-label="下一个月" icon={<RightOutlined/>} onClick={()=>shift(1)} disabled={start.y*12+start.m>=cy*12+cm-2}/></Space><div style={{display:"flex",flexDirection:mobile?"column":"row",gap:28,flexWrap:"wrap"}}>{months.map(m=><Month key={`${m.y}-${m.m}`} year={m.y} month={m.m} days={studyDays}/>)}</div></Card></main>}
